# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_account = QtWidgets.QPushButton(Form)
        self.btn_account.setObjectName("btn_account")
        self.horizontalLayout.addWidget(self.btn_account)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(33)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_total = QtWidgets.QLabel(Form)
        self.lb_total.setObjectName("lb_total")
        self.horizontalLayout_2.addWidget(self.lb_total)
        self.lb_today = QtWidgets.QLabel(Form)
        self.lb_today.setObjectName("lb_today")
        self.horizontalLayout_2.addWidget(self.lb_today)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_rec = QtWidgets.QPushButton(Form)
        self.btn_rec.setObjectName("btn_rec")
        self.verticalLayout.addWidget(self.btn_rec)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_account.setText(_translate("Form", "账号信息"))
        self.label.setText(_translate("Form", "如厕记录器"))
        self.lb_total.setText(_translate("Form", "累记如厕："))
        self.lb_today.setText(_translate("Form", "今日如厕："))
        self.btn_rec.setText(_translate("Form", "记录如厕"))
